---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=${ADDRESS}
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASSWORD=${PASSWORD}
      - DB_DATABASE=bookstackapp
    volumes:
      - ${BOOKSTACK_CONFIG_DIRECTORY}:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=${PASSWORD}
    volumes:
      - ${BOOKSTACK_DB_DIRECTORY}:/db-config
    ports:
      - 6876:3306
    restart: unless-stopped
