version: '3'
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '${ACTUAL_PORT}:5006'
    volumes:
      - ${ACTUAL_DATA_DIRECTORY}:/data
    restart: unless-stopped